<?php
// NE PAS MODIFIER
DEFINE("_HOST", "localhost");
DEFINE("_USER", "root");
DEFINE("_PASS", "");
DEFINE("_BASE_DE_DONNEES", "startup_simulator");

// FACEBOOK
DEFINE('FACEBOOK_APP_ID', '');
DEFINE('FACEBOOK_APP_SECRET', '');

DEFINE('ADMIN_MAIL', '');
DEFINE('MAIL_SERVER', 0);
DEFINE('DEBUG', 0);
DEFINE('PROFILER', 0);
DEFINE('LOG', 1);
DEFINE('LOG_FILE', 'startup.log');